Repository Susmita-Dey/Moody, pull requests merged in 2022-10, with the labels that each got.

#17 Updated Readme for the project.
  README.md
Labels: documentation, hacktoberfest-accepted

#23 Loading animation added Made Responsive the Extension and Ui changed
  assets/emojis/emoji-angry.png
  assets/emojis/emoji-angry.svg
  assets/emojis/emoji-frown.svg
  assets/emojis/emoji-laughing.png
  assets/emojis/emoji-laughing.svg
  assets/emojis/sad.png
  css/cooking.css
  css/style.css
  index.html
  js/jokes.js
  pages/cooking.html
  pages/sad.html
Labels: enhancement, hacktoberfest-accepted

#16 added Moody website link in readme
  README.md
Labels: documentation

#25 Hover Effect added on sad.html page buttons
  pages/sad.html
Labels: enhancement, hacktoberfest-accepted

#27 fetching animation and search icon added
  assets/search-icon.png
  css/cooking.css
  js/recipe.js
  pages/cooking.html
Labels: enhancement, hacktoberfest-accepted

#30 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#31 Update anxious.html
  pages/anxious.html
Labels: enhancement, hacktoberfest-accepted
